import type {
  Club,
  CompetitionEvent,
  DashboardData,
  Registration,
  School,
} from "@/lib/types";

export const demoSchools: School[] = [
  {
    id: "school-1",
    school_id: "school-1",
    name: "Stellar Institute of Technology",
    slug: "stellar-institute-of-technology",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    description: "Known for campus competitions, design culture, and strong club communities.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "school-2",
    school_id: "school-2",
    name: "Rivergate College",
    slug: "rivergate-college",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    description: "Hosts high-traffic technical fests and inter-college circuits.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoClubs: Club[] = [
  {
    id: "club-1",
    school_id: "school-1",
    name: "Code Forge",
    slug: "code-forge",
    category: "Technology",
    description: "Hackathons, product sprints, and coding battles.",
    contact_email: "codeforge@stellar.edu",
    logo_url: null,
    created_by: "demo-user",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "club-2",
    school_id: "school-1",
    name: "Stage Riot",
    slug: "stage-riot",
    category: "Cultural",
    description: "Performance, public speaking, and expression on stage.",
    contact_email: "stageriot@stellar.edu",
    logo_url: null,
    created_by: "demo-user",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoEvents: CompetitionEvent[] = [
  {
    id: "event-1",
    school_id: "school-1",
    club_id: "club-1",
    organizer_id: "demo-user",
    title: "Compeat Build Sprint",
    slug: "compeat-build-sprint",
    description:
      "A 24-hour product sprint for campus teams building event-tech tools.",
    category: "Hackathon",
    city: "Bengaluru",
    venue: "Innovation Block A",
    poster_url: null,
    registration_deadline: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    starts_at: new Date(Date.now() + 1000 * 60 * 60 * 96).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 60 * 120).toISOString(),
    capacity: 180,
    status: "published",
    visibility: "public",
    allows_cross_school: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    schools: {
      id: "school-1",
      name: "Stellar Institute of Technology",
      city: "Bengaluru",
      country: "India",
    },
    clubs: { id: "club-1", name: "Code Forge" },
    registrations_count: 72,
  },
  {
    id: "event-2",
    school_id: "school-2",
    club_id: null,
    organizer_id: "demo-user",
    title: "Rivergate Debate Open",
    slug: "rivergate-debate-open",
    description:
      "Inter-college debate tournament with novice and open divisions.",
    category: "Debate",
    city: "Chennai",
    venue: "Auditorium 3",
    poster_url: null,
    registration_deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4).toISOString(),
    starts_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 8).toISOString(),
    capacity: 90,
    status: "published",
    visibility: "public",
    allows_cross_school: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    schools: {
      id: "school-2",
      name: "Rivergate College",
      city: "Chennai",
      country: "India",
    },
    clubs: null,
    registrations_count: 38,
  },
];

export const demoRegistrations: Registration[] = [
  {
    id: "registration-1",
    school_id: "school-1",
    event_id: "event-1",
    user_id: "demo-user",
    participant_school_id: "school-1",
    status: "approved",
    notes: "Team Alpha",
    certificate_path: "certificates/demo-user/build-sprint.pdf",
    certificate_url: "#",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    events: {
      id: "event-1",
      title: "Compeat Build Sprint",
      starts_at: new Date(Date.now() + 1000 * 60 * 60 * 96).toISOString(),
      venue: "Innovation Block A",
    },
  },
  {
    id: "registration-2",
    school_id: "school-2",
    event_id: "event-2",
    user_id: "demo-user",
    participant_school_id: "school-1",
    status: "pending",
    notes: null,
    certificate_path: null,
    certificate_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    events: {
      id: "event-2",
      title: "Rivergate Debate Open",
      starts_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
      venue: "Auditorium 3",
    },
  },
];

export const demoDashboardData: DashboardData = {
  clubs: demoClubs,
  events: demoEvents,
  registrations: demoRegistrations,
  certificates: demoRegistrations.filter((registration) => registration.certificate_url),
};
